---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: 42.62.51.57/test/hello-world:master-a4a9c1fe
        ports:
        - containerPort: 8080
