---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: harbor.raginghot.com.cn/test/hello-world:master-70961665b
        ports:
        - containerPort: 8080
